Updated the fizzbuzz code as per the Doug's feedback:
1.Added /usr/bin/env because this helps in looking for the default version of the program is in the current environment.
2.Added the exit code to exit when the command fails, when using the undeclared variables and pipeline failure
3.Updated the function names to fizzbuzz and main so that the funaction names are self-explantory of what the function is doing.
4.Updated the global variables to local variables since they are not used outside the function.
5.Updated the shell command for range (seq 1 100) to Bash range. Since the whole code is in Bash language.Updated the fizzbuzz code as per the Doug's feedback.

diff --git a/fizzbuzz b/fizzbuzz
--- a/fizzbuzz
+++ b/fizzbuzz
@@ -1,11 +1,11 @@
-#!/bin/bash
-#first function that prints the return value from the second function
+#!/usr/bin/env bash
+#main function that prints the return value from the second function
 #work: 
 #   Step1:the loop will run 100 times, once for each number between 1 and 100
 #   Step2:it will pass that number as argument to the second function
 #output (print): print the return value from the second function.
 
-#second function that returns each number from 1 to 100 by replacing the number with fizz or buzz or fizzbuzz
+#fizzbuzz function that returns each number from 1 to 100 by replacing the number with fizz or buzz or fizzbuzz
 #input (parameters) = 1 number from 1 to 100
 #work:
 #	Step1: check whether the number is divisible by both 3&5.
@@ -27,23 +27,31 @@
 #      input:21
 #      output:fizz
 
-function second(){
-   if (( $1 % 3 == 0 )) && (( $1 % 5 == 0 ));then
-       var="fizzbuzz"
-   elif (( $1 % 3 == 0 ));then
-       var="fizz"
-   elif (( $1 % 5 == 0 ));then
-       var="buzz"
+
+set -o errexit
+set -o pipefail
+set -o nounset
+
+function fizzbuzz {
+    local number=$n
+   if (( "$number" % 3 == 0 )) && (( "$number" % 5 == 0 ));then
+        echo fizzbuzz
+   elif (( "$number" % 3 == 0 ));then
+        echo fizz
+   elif (( "$number" % 5 == 0 ));then
+        echo buzz
    else
-       var=$n
+        echo "$number"
    fi    
 }
 
-function first(){
-    for n in $(seq 1 100)
+function main {
+    for n in {1..100};
 do
-    second n
-    echo "$var"
+    local result
+    result=$(fizzbuzz n)
+    echo "$result"
+
 done
 }
-first
+main
